# -*- coding: utf-8 -*-
"""Data Science Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PtDQsAo5Kfe7JOhmSZ4fBPs-9IIBmo3P
"""

import pandas as pd
import numpy as np

df = pd.read_excel("Online Retail.xlsx")
df.head()

print("Shape of dataset:",df.shape)
print("\nData types and missing values:", df.info())
print("\nFirst 5 rows:\n",df.head())

df.dropna(subset=["CustomerID"], inplace=True)

df.drop_duplicates(inplace=True)